version: '3'
services:
  
  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: LaravelDock/php
    container_name: laraveldockPHP
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
   

  #Nginx
  webserver:
    image: nginx:alpine
    container_name: laraveldockWebserver
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
   

  #MySQL
  db:
    image: mysql:5.7.22
    container_name: laraveldockDB
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: arsys
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: Ddw8436
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    

#Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local