version: '3'
services:
  
  #PHP
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: l11/php
    container_name: l11PHP
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
   

  #Nginx
  webserver:
    image: nginx:alpine
    container_name: l11Webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8005:80"
      - "444:443"
    volumes:
      - ./:/var/www
      - ./nginx/:/etc/nginx/conf.d/
   

  #MySQL
  db:
    image: mysql:5.7.22
    container_name: l11DB
    restart: unless-stopped
    tty: true
    ports:
      - "3310:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
  

#Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local